### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [FriesI23/mhabit#102]
Please add direct cryptocurrency addresses within the app. I don't want going around to websites. I don't want support FIAT economy.

TRX, AVAX, LTC, BTC, XEC, BNB, SOL, BCH, ALGO, XTZ, DASH, FTM, XMR addresses available for donations.

**Comment by Miaaaim** [comment]
I haven't used cryptocurrency before, so I need to learn more about it first and consider adding cryptocurrency addresses in future versions.

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Donation Channel Supports Cryptocurrency](https://trello.com/c/DR0sXnly/50-donation-channel-supports-cryptocurrency)

**Comment by FriesI23** [comment]
> I added the BNB (Smart Chain) coin to first post. Low fees, fast finality (transactions). For the same reasons I recommend the AVAX (Avalanche) token too. You can find both in UW.

Thanks alot, i will add it later 😉.

**Comment by FriesI23** [comment]
not complete yet

**Comment by FriesI23** [comment]
Thank you for your donation first!  
The main purpose of this app is to help users develop habits (rather than remind to donate), So it's more appropriate to place donate button here. 

However, there is a bit of issues with the implementation of these buttons. I will reopen this issue and make some optimizations (include fixing typo errors).

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Optimize the donate dialog](https://trello.com/c/DCXxWoxS/55-optimize-the-donate-dialog)
