### ISSUE TITLE
[BUG] No notification alert and even crash when notification should pop up

### ISSUE THREAD

**Issue by JoeHardi** [FriesI23/mhabit#147]
## Before reporting bug, make sure the following options

- [x] Check for the Latest Version [HERE](https://github.com/FriesI23/mhabit/releases/latest)
- [x] Search for Existing Issues [HERE](https://github.com/FriesI23/mhabit/issues?q=is%3Aissue)
- [x] Verify if this BUG can be reproduced

---

**Description**
I try to set up a notification e.g. at 9 a.m. every morning. I never get a norification and sometimes even a crash pop up that "Table Habit" stopped working. MicroG is deactivated but activated on work profile. Doesnt work there either.

**Step to Reproduce**
1. I have the latest version installed via F-Droid.
2. No existing issue, from what I saw.
3. Happens every times with every habit.

**Expected Behavior**
To get a pop up notification at the time set up.

**Device/Environment Info**
Sony Xperia 5 III
LineageOS Version: 20-20240213-microG-pdx214
Android 13
MicroG deactivated

**Comment by FriesI23** [comment]
lastest version [v1.10.6](https://github.com/FriesI23/mhabit/releases/tag/v1.10.6%2B34) fixed this issue. please update to this version and verify if the issue still persists. (Due to the F-Droid build cycle, updates might be delayed,  but there should be the latest version available now)

I will close this issue for now. If the problem persists, please post feedback below, and I will reopen the issue 😉.

**Comment by FriesI23** [comment]
linked #144
