### ISSUE TITLE
[FEATURE] Ability to set folder for storing opened data externally

### ISSUE THREAD

**Issue by toropanov** [FriesI23/mhabit#148]
I utilize Obsidian to gather all my data from to-dos, diary entries, and other sources in order to analyze it.

I really love the Daily Habit app that you created, it's perfect for daily use. However, I have a suggestion. Could you please add an option to set a folder to store data? It would be great if the data could be stored in an open format like JSON, etc. Thank you!

I can't speak for others, but I personally need this data in my Obsidian folder in order to parse it in real time.

**Comment by FriesI23** [comment]
Hi, thank you for your feedback.

Currently, the data is stored in SQLite, and due to the privacy isolation in new version Android, non-rooted phones may not be able to access the `data` directory properly. 
So, there's no plan to add plain text way to store data. However, now can export habit data in pure text json format through `export` feature.
