### ISSUE TITLE
[Feature Request] Unlimited Target Days

### ISSUE THREAD

**Issue by chromer030** [FriesI23/mhabit#41]

**Comment by FriesI23** [comment]
This is not the intended behavior of this app. In terms of design, this app aim for users to complete and archive all their habits rather than keeping them ongoing indefinitely. 

For habits that are meant to be ongoing indefinitely, a to-do app maybe a better choice. for example, `Task.org` is a better choice in this case! ☺️

**Comment by chromer030** [comment]
What about the habits that never ends ? like running push ups etc , or reading books etc
